//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public string Answers { get; set; }
        public int Answer_id { get; set; }
        public Nullable<int> QuestionID { get; set; }
        

    
        public virtual Question Question { get; set; }
    }
}
